Consistently print 'Error:' on failures and do not add usage
`gb/remote/gb-remote-log` will pass `Error:` into error.log which is
useful. Otherwise, we can get unrelated messages there which is confusing
to users. (Such as happened for absence of `--klog` options from 6.12
kernel when built in old branches.)

Before:

  [x86_64] init: mount sysfs to /sys
  [x86_64] init: no virtio_console device driver (1): No such file or directory
  [x86_64] init: mount 9p from virtio-9p:/ to /newroot flags 'version=9p2000.L,trans=virtio,access=any,msize=262144'
  [x86_64] --
  [x86_64] + cat /usr/lib/ltp/output/LTP_RUN_ON-out.failed
  [x86_64] cat: /usr/lib/ltp/output/LTP_RUN_ON-out.failed: No such file or directory

After:

  [x86_64] init: mount sysfs to /sys
  [x86_64] init: no virtio_console device driver (1): No such file or directory
  [x86_64] init: mount 9p from virtio-9p:/ to /newroot flags 'version=9p2000.L,trans=virtio,access=any,msize=262144'
  [x86_64] --
  [x86_64] + timeout 999 vm-run --kvm=cond --klog --append=altha=1 runltp -f kernel-alt-vm -S skiplist-alt-vm -o out
  [x86_64] Error: Unknown option --klog
  [x86_64] + cat /usr/lib/ltp/output/LTP_RUN_ON-out.failed
  [x86_64] cat: /usr/lib/ltp/output/LTP_RUN_ON-out.failed: No such file or directory

Signed-off-by: Vitaly Chikunov <vt@altlinux.org>

diff --git a/vm-create-image b/vm-create-image
--- a/vm-create-image
+++ b/vm-create-image
@@ -89,7 +89,7 @@ for opt; do # opt
 		--mkfs=*)       mkfs+=" $arg" ;;
 		-v | --verbose) verbose+=1 ;;
 		-h | --help)    show_usage ;;
-		-*)             fatal "Unknown option $opt" ;;
+		-*)             fatal "Error: Unknown option $opt" ;;
 		*)              set -- "$@" "$opt" ;;
 	esac
 done
@@ -167,7 +167,7 @@ elif [ -v copy_mode ]; then
 	[ $# -gt 2 ] && fatal "Too much arguments for cp mode"
 	info=$(/sbin/debugfs "$image" -R "stat $1" 2>&1 | head -2)
 	if [[ "$info" =~ File.not.found ]]; then
-		echo "$info" >&2
+		echo "Error: $info" >&2
 		exit 1
 	elif [[ "$info" =~ Type:.directory ]]; then
 		mkdir -p "$2"
diff --git a/vm-run b/vm-run
--- a/vm-run
+++ b/vm-run
@@ -104,7 +104,7 @@ usage() {
 	echo "    --verbose        Show vm actions verbosely"
 	echo "    --               No options after this marker"
 	echo "    command...       Will be eval'ed on the target"
-	exit 1
+	exit 0
 }
 
 while [ $# -gt 0 ]; do # opt
@@ -181,7 +181,7 @@ while [ $# -gt 0 ]; do # opt
 		-virtfs|-vnc|-watchdog-action|-xen-domid \
 			) shift; OPTS+=" $opt ${1:?"$opt requires argument"}" ;;
 		--) shift; break ;;
-		-*) echo "Unknown option $opt" >&2; usage ;;
+		-*) echo "Error: Unknown option $opt" >&2; exit 1 ;;
 		*)  break ;;
 	esac
 	shift
