vm-create-image: Warn about buggy e2fsprogs
e2fsprogs-1.44.6-alt1 in p9 creates broken images with debugfs reporting
(which is visible oony in verbose mode) a lot of `File not found by
ext2_lookup` error message.

Then system doesn't boot with:

  init: mount ext4 from /dev/vda to /newroot flags ''
  [    0.826951] EXT4-fs (vda): recovery complete
  [    0.827351] EXT4-fs (vda): mounted filesystem with ordered data mode. Opts: (null)
  init: switch root
  init: exec '/usr/lib/vm-run/vm-init'
  init: execv '/usr/lib/vm-run/vm-init': No such file or directory

Signed-off-by: Vitaly Chikunov <vt@altlinux.org>

diff --git a/vm-create-image b/vm-create-image
--- a/vm-create-image
+++ b/vm-create-image
@@ -321,6 +321,12 @@ generate_debugfs_commands() {
 	}
 }
 
+e2pkg=$(rpm -q --qf '%{VERSION}' e2fsprogs)
+e2ok='1.46.2'
+if printf '%s\n%s\n' "$e2pkg" "$e2ok" | sort -CV; then
+	echo >&2 "WARNING: e2fsprogs version below $e2ok is known to fail to create correct ext4 image!"
+fi
+
 for dir in "${src[@]}"; do
 	generate_debugfs_commands "$dir" | ($SETX; /sbin/debugfs -f- -w "$image") >&"$NULL"
 done
