vm-initrd: Make modprobe optional
In theory it could be called without `--modules=`.

Signed-off-by: Vitaly Chikunov <vt@altlinux.org>

diff --git a/vm-initrd b/vm-initrd
--- a/vm-initrd
+++ b/vm-initrd
@@ -96,15 +96,17 @@ for m in $MODULES; do
 		MODS+=" $pre $m $post"
 	fi
 done
-MODULES=$MODS
+MODULES=${MODS# }
 unset MODS
+true > "$CPIO/modprobe.txt"
 # shellcheck disable=SC2086
-if ! /sbin/modprobe -d "$ROOT" -S "$KVER" -D -a $MODULES > "$CPIO/modprobe.txt"; then
-	echo "Error: modprobe failure." >&2
+if [ -n "$MODULES" ] &&
+   ! /sbin/modprobe -d "$ROOT" -S "$KVER" -D -a $MODULES > "$CPIO/modprobe.txt"; then
+	echo "initrd: Error: modprobe failure." >&2
 	if [ ! -s "$ROOT/lib/modules/$KVER/modules.dep.bin" ]; then
 		[ -w "$ROOT/lib/modules/$KVER/" ] && HELP= \
 			|| HELP=" under rooter"
-		echo "  Run 'depmod${ROOT:+ -b $ROOT} $KVER'$HELP." >&2
+		echo "initrd:   Run 'depmod${ROOT:+ -b $ROOT} $KVER'$HELP." >&2
 	fi
 	exit 1
 fi
