vm-run: Add experimental '--stdout' option
Redirect VM messages to stderr, but command output to stdout. (Using
QEMU virtio-serial's virtserialport and virtio-console module.)

Required change: before console is set up vm-init output is still
directed to stdout (i.e. to console), but after it's set up redirect
messages to to stderr, so they don't clutter possible stdout.

Notes: chardev 'pipe' is bi-directional, but this somehow does not work
to setup this device also for stdin. 'file' produces EPERM, 'socket'
ENOENT. 'stdio' works perfectly for stdin, but it's hard-coded to use FD
1 for stdout (thus not suitable for swapping FDs).

TTY support does not work either. I guess system not likes different
consoles on a single stdio. So stdout (while no other ideas yet) is
always non-TTY. Console is left for stdin to read the data if any.

Overall no options works perfectly making this too complicated and
experimental.

Even if some trick would work, there is still problem of EOF which does
not pass into VM, so 'vm-run cat </dev/null' hangs forever.

Signed-off-by: Vitaly Chikunov <vt@altlinux.org>

diff --git a/vm-init b/vm-init
--- a/vm-init
+++ b/vm-init
@@ -76,6 +76,17 @@ else
 	echo "vm-init: console=$CONSOLE is not accessible."
 fi
 
+if [ -n "$STDOUT" ]; then
+	for vport in /sys/class/virtio-ports/*; do
+		read name < "$vport/name"
+		if [ "$name" = stdout ]; then
+			name=$(basename "$vport")
+			exec 1>/dev/"$name"
+		fi
+	done
+	unset STDOUT vport name
+fi
+
 install -g utmp -m660 /dev/null /var/log/btmp
 install -g utmp -m664 /dev/null /var/log/wtmp
 
@@ -118,8 +129,8 @@ unset SWAPSIZE SWAPDEV
 if tmp=$(mktemp -p /usr/src 2>/dev/null); then
 	rm $tmp
 else
-	echo "  Error: Impossible to create files in /usr/src"
-	echo "         Exit code from the command will be lost!"
+	echo >&2 "  Error: Impossible to create files in /usr/src"
+	echo >&2 "         Exit code from the command will be lost!"
 fi
 
 # Prepare network
@@ -193,7 +204,7 @@ while [ -z "${prev_cmdline/* OVERLAY=*}" ]; do
 		V mount $V -t ext4 -o loop $img $mnt
 		img_count=$((img_count+1))
 	else
-		echo "Unknown how to overlay $OVERLAY"
+		echo >&2 "Unknown how to overlay $OVERLAY"
 		unset mnt
 	fi
 	if [ "$mnt" ]; then
@@ -214,17 +225,17 @@ if [ -n "$RUNUSER" ]; then
 	RUNUSER="/usr/lib/vm-run/vm-fakesudo -u $RUNUSER -i exec"
 fi
 
-[ -z "$NOTTY" ] && V vm-resize ${V:--q}
+[ -z "$NOTTY" ] && [ -t 1 ] && V vm-resize ${V:--q}
 
 if [ -f "$SCRIPT" ]; then
 	set -- $SCRIPT
 else
-	echo "vm-init: SCRIPT=$SCRIPT not found, running rescue shell."
+	echo >&2 "vm-init: SCRIPT=$SCRIPT not found, running rescue shell."
 	unset RUNUSER
 	export PS1='(rescue)# '
 	set -- /bin/bash
 fi
-$RUNUSER setsid --ctty --wait "$@"
+$RUNUSER setsid $(test -t 1 && echo --ctty) --wait "$@"
 RET=$?
 # TODO: We can miss some stderr output here, for example script is not
 # executable due to incorrect TMPDIR.
@@ -232,7 +243,7 @@ RET=$?
 [ "$UMOUNT" ] && umount $V -n --lazy $UMOUNT
 case "$SCRIPT" in /tmp/*) umount $V -n --lazy /tmp;; esac
 echo $RET 2>/dev/null > "$SCRIPT.ret" ||
-	echo Exit code $RET is lost
+	echo >&2 "Exit code $RET is lost"
 
 # Disable `reboot: Power down' message
 [ -z "${cmdline/* quiet *}" ] && echo 0 > /proc/sys/kernel/printk
