vm-run: Attribute failure message
Signed-off-by: Vitaly Chikunov <vt@altlinux.org>

diff --git a/vm-run b/vm-run
--- a/vm-run
+++ b/vm-run
@@ -1006,6 +1006,6 @@ if [ -s $SCRIPT.ret ]; then
 	exit $ret
 else
 	# Possible kernel crash or C-a x
-	echo "  Error: no exit code is found, failure." >&2
+	echo "vm-run: Error: no exit code is found, failure." >&2
 	exit 1
 fi
