vm-run: Allow --bios=u-boot shortcut
Requires to install u-boot-qemu. Available on:

  $ grep qemu.*u-boot.bin /ALT/Sisyphus/*/base/contents_index
  /ALT/Sisyphus/aarch64/base/contents_index:/usr/share/u-boot/qemu_arm64/u-boot.bin	u-boot-qemu
  /ALT/Sisyphus/armh/base/contents_index:/usr/share/u-boot/qemu_arm/u-boot.bin	u-boot-qemu
  /ALT/Sisyphus/i586/base/contents_index:/usr/share/u-boot/qemu-x86/u-boot.bin 	u-boot-qemu
  /ALT/Sisyphus/x86_64/base/contents_index:/usr/share/u-boot/qemu-x86_64/u-boot.bin	u-boot-qemu

Signed-off-by: Vitaly Chikunov <vt@altlinux.org>

diff --git a/vm-run b/vm-run
--- a/vm-run
+++ b/vm-run
@@ -319,6 +319,16 @@ elif [ "$BIOS" = "secureboot" ]; then
 	fi
 elif [ "$BIOS" = "microvm" ]; then
 	OPTS+=" -bios bios-microvm.bin"
+elif [ "$BIOS" = "u-boot" ]; then
+	set +f
+	u_boot=( /usr/share/u-boot/qemu*/u-boot.bin )
+	set -f
+	if [ ! -e "$u_boot" ]; then
+		echo "Error: Das U-Boot is not available for this system (install u-boot-qemu)." >&2
+		exit 1
+	fi
+	OPTS+=" -bios $u_boot"
+	unset u_boot
 elif [ -f "/usr/share/qemu/$BIOS" ]; then
 	OPTS+=" -bios $BIOS"
 elif [ -n "$BIOS" ]; then
