Add --kvm=cond option for conditional run
Use `--kvm=cond' for conditional run instead of previously suggested
`[ -w /dev/kvm ]' test, which was not reliable (on armh).

All `--kvm=' options:

  --kvm=try   try to use KVM if available (detect by vm-run), otherwise
              (without a warning) fallback to TCG (this is the default);
  --kvm=off   (same as --tcg) disable KVM;
  --kvm=only  enable KVM or fail (exit 1);
  --kvm=cond  enable KVM or success (exit 0);
  --kvm=all   tell qemu to try to use KVM, otherwise it will issue a
              warning and fallback to TCG;
  --kvm=default  do not specify accel, but rely on qemu defaults.

kvm_ok test is Co-developed-with: Dmitry V. Levin <ldv@altlinux.org>

diff --git a/vm-run b/vm-run
--- a/vm-run
+++ b/vm-run
@@ -28,7 +28,7 @@ MAXMEM=
 MAXCPU=
 DEPMOD=
 BIOS=
-KVM=yes		# try to use kvm by default
+KVM=try		# try to use kvm by default
 VIRTIOBUS=pci	# virtio bus to use
 
 usage() {
@@ -51,6 +51,7 @@ usage() {
 	echo "    --secureboot     Use OVMF SecureBoot fw (alias --bios=secureboot)"
 	echo "    --microvm        Use microvm machine"
 	echo "    --tcg            Do not try to enable KVM"
+	echo "    --kvm=cond       Only run if KVM is present otherwise exit 0"
 	echo "    --mem=           pass '-m ...' to qemu (memory size)"
 	echo "    --cpu=           pass '-smp ...' to qemu (cpus)"
 	echo "    --kernel=        kernel version to use (--kernels to list)"
@@ -78,6 +79,7 @@ for opt do
 		--securebo*) BIOS=secureboot ;;
 		--bios=*)    BIOS="${opt#*=}" ;;
 		--tcg)	     KVM= ;;
+		--kvm=*)     KVM="${opt#*=}" ;;
 		--microvm)   VIRTIOBUS=device OPTS+=" -M microvm" BIOS=microvm ;;
 		--machine=*) OPTS+=" -machine ${opt#*=}" ;;
 		--global=*)  OPTS+=" -global ${opt#*=}" ;;
@@ -126,13 +128,28 @@ printf  "\n" >> $SCRIPT
 printf  "RET=\$?\nstty sane\nexit \$RET\n" >> $SCRIPT
 chmod a+rx $SCRIPT
 
+kvm_ok() {
+	if [ -c /dev/kvm -a -w /dev/kvm ]; then
+		true < /dev/kvm
+	else
+		false
+	fi 2>/dev/null
+}
+
+kvm_need() {
+	case "$KVM" in
+		no|off|false|tcg|"") false ;;
+		*) true ;;
+	esac
+}
+
 ppc_opts() {
 	# Use `power8' and not `host', because we will transparently
 	# fallback from kvm to tcg. All following options will not
 	# break fallback to tcg.
 	echo -n " -M cap-ibs=broken,cap-cfpc=broken,cap-sbbc=broken"
 	echo -n " -cpu power8"
-	if [ -n "$KVM" -a -w /dev/kvm ]; then
+	if kvm_need && kvm_ok; then
 		# In absence of `/usr/sbin/ppc64_cpu' determine SMT by presence
 		# online cores 1-7, (while cores 0,8,.. is not SMT cores.)
 		if grep -q -P '^processor\s+:\s[1234567]$' /proc/cpuinfo; then
@@ -234,16 +251,40 @@ elif [ -e /usr/share/qemu/bios.bin ]; then
 	OPTS+=" -bios bios.bin"
 fi
 
-# If KVM is accessible use it.
-if [ -n "$KVM" ]; then
-	if [ -w /dev/kvm ]; then
-		# Fallback to TCG in case of something.
-		DEF+=" -M accel=kvm:tcg"
-	fi
+if kvm_need; then
+	case "$KVM" in
+		try|detect)
+			# Avoid qemu warning:
+			#   Could not access KVM kernel module: No such file or directory
+			#   qemu-system-x86_64: failed to initialize kvm: No such file or directory
+			#   qemu-system-x86_64: falling back to tcg
+			kvm_ok && DEF+=" -M accel=kvm:tcg" || DEF+=" -M accel=tcg"
+			;;
+		cond|if)
+			if ! kvm_ok; then
+				echo "Warning: Not running due to no KVM support (exit 0)."
+				exit 0
+			fi
+			DEF+=" -enable-kvm"
+			;;
+		only|force|enable)
+			DEF+=" -enable-kvm"
+			;;
+		any|all)
+			DEF+=" -M accel=kvm:tcg"
+			;;
+		default)
+			;;
+		*)
+			echo "Error: Unknown --kvm=$KVM option."
+			exit 1
+			;;
+	esac
 else
 	# Forcefully disable KVM.
-	DEF+=" -M accel=tcg"
+	DEF+=" -accel tcg"
 fi
+unset KVM
 
 if ! mountpoint -q /proc; then
 	echo "===========================================" >&2
