Do not run depmod for %buildroot automatically
This is to prevent accidental mangling of %buildroot in %check.
Perhaps, this will also make depmod call useless.

diff --git a/vm-run b/vm-run
--- a/vm-run
+++ b/vm-run
@@ -26,6 +26,7 @@ QUIET=quiet	# no boot messages
 DEF=
 MAXMEM=
 MAXCPU=
+DEPMOD=
 
 usage() {
 	echo "Usage: $0 [options] command..."
@@ -44,6 +45,7 @@ usage() {
 	echo "    --mem=           pass '-m ...' to qemu (memory size)"
 	echo "    --cpu=           pass '-smp ...' to qemu (cpus)"
 	echo "    --kernel=        kernel version to use (--kernels to list)"
+	echo "    --depmod         auto-depmod %buildroot installed kernel"
 	echo "    --               no options after this marker"
 	echo "    command...       will be eval'ed on the target"
 	exit 1
@@ -66,6 +68,7 @@ for opt do
 		--cpu=*)     OPTS+=" -smp ${opt#*=}" ;;
 		--kernel=*)  KERNEL="${opt#*=}" ;;
 		--kernel*)   KERNEL= ;;
+		--depmod)    DEPMOD=y ;;
 		--) break ;;
 		-*) echo "Unknown option $opt $*" >&2; usage ;;
 		*)  set -- "$opt" "$@"; break ;;
@@ -306,9 +309,20 @@ if [ ! -f "${INITRD-}" ]; then
 		echo "       Please, install the kernel or make modules_install!"  >&2
 		exit 1
 	fi
-	if [ ! -s "$ROOT/lib/modules/$KVER/modules.dep.bin" ] &&
-	   [ -w "$ROOT/lib/modules/$KVER" ]; then
-		   ( set -x; /sbin/depmod ${ROOT:+-b $ROOT} $KVER )
+	if [ ! -s "$ROOT/lib/modules/$KVER/modules.dep.bin" ]; then
+		if [ -w "$ROOT/lib/modules/$KVER" ]; then
+			if [ -z "$DEPMOD" ] && [[ "$ROOT" =~ buildroot ]]; then
+				echo "  Run 'depmod -b $ROOT $KVER'" >&2
+				echo "  or start vm-run with '--depmod' option for automatic depmod." >&2
+				exit 1
+			else
+				( set -x; /sbin/depmod ${ROOT:+-b $ROOT} $KVER )
+			fi
+		else
+			echo "Error: No valid 'modules.dep.bin' in $ROOT/lib/modules/$KVER"  >&2
+			echo "       which is also not writable directory. As a result 'modprobe' will not work!"  >&2
+			exit 1
+		fi
 	fi
 	INITRD=${TMPDIR:-/tmp}/initramfs-$KVER.img
 	CPIO=$(mktemp -d)
