vm-run: Allow additional options for rootfs after comma
For example if you want IMAGE not modified after boot you can pass:

  --rootfs=IMAGE,snapshot=on

Automatic options still apply.

Signed-off-by: Vitaly Chikunov <vt@altlinux.org>

diff --git a/vm-run b/vm-run
--- a/vm-run
+++ b/vm-run
@@ -386,29 +386,30 @@ if [ -e /proc/net/dev ] && [ $(wc -l < /proc/net/dev) -gt 3 ]; then
 fi
 
 if [ -n "$ROOTFS" ]; then
-	[ -z "$ROOTFSCREATE" ] || vm-create-image "$ROOTFS"
-	FORMAT=$(qemu-img info "$ROOTFS" | grep -Po 'file format: \K.*')
+	ROOTFSFILE=${ROOTFS%,*}
+	[ -z "$ROOTFSCREATE" ] || vm-create-image "$ROOTFSFILE"
+	FORMAT=$(qemu-img info "$ROOTFSFILE" | grep -Po 'file format: \K.*')
 	if [ "$FORMAT" = "qcow2" ]; then
 		tmpfile=$(mktemp)
-		qemu-img dd if="$ROOTFS" of="$tmpfile" count=4
+		qemu-img dd if="$ROOTFSFILE" of="$tmpfile" count=4
 		eval "$(/sbin/blkid -o export -- "$tmpfile")"
 		rm $tmpfile
 	elif [ "$FORMAT" = "raw" ]; then
-		eval "$(/sbin/blkid -o export -- "$ROOTFS")"
+		eval "$(/sbin/blkid -o export -- "$ROOTFSFILE")"
 	else
-		echo "Error: Image '$ROOTFS' in unsupported format '$FORMAT'."
+		echo "Error: Image '$ROOTFSFILE' in unsupported format '$FORMAT'."
 		exit 1
 	fi
 	if [[ ! "${TYPE-}" =~ ^ext[234]$ ]]; then
-		echo "Error: ext4 filesystem not found in '$ROOTFS'." >&2
+		echo "Error: ext4 filesystem not found in '$ROOTFSFILE'." >&2
 		exit 1
 	fi
 	OPTS+=" -drive file=$ROOTFS,if=virtio"
 	[ "$FORMAT" = "raw" ] && OPTS+=",format=raw"
-	[ -w "$ROOTFS" ] || OPTS+=",snapshot=on"
+	[ -w "$ROOTFSFILE" ] || OPTS+=",snapshot=on"
 	APPEND+=" root=UUID=$UUID rootfstype=$TYPE"
 	MODULES+=" virtio-blk"
-	unset FORMAT
+	unset FORMAT ROOTFSFILE
 fi
 # We shall load these modules even though we're using ext4 for rootfe
 # (but supposedly we can mount 9p later and modprobe before that).
